set_property PACKAGE_PIN B2 [get_ports {mode[2]}]
set_property PACKAGE_PIN C1 [get_ports {mode[1]}]
set_property PACKAGE_PIN C3 [get_ports {mode[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mode[0]}]
set_property PULLDOWN true [get_ports {mode[1]}]
set_property PULLDOWN true [get_ports {mode[0]}]
set_property PULLDOWN true [get_ports {mode[2]}]
set_property PACKAGE_PIN D4 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN T9 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property PACKAGE_PIN P3 [get_ports pwm_out]
set_property IOSTANDARD LVCMOS33 [get_ports pwm_out]

